  services:
    traefik:
      image: "traefik:latest"
      container_name: traefik
      command:
        - "--log.level=DEBUG"
        - "--api.insecure=true"
        - "--providers.docker=true"
        - "--entryPoints.web.address=:80"
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      ports:
        - 80:80
        - ${TRAEFIK_PORT}:8080
      labels:  
        - traefik.enable=true
        - traefik.http.routers.${TRAEFIK_REF}.entrypoints=web
        - traefik.http.routers.${TRAEFIK_REF}.rule=Host(`${HOST_TRAEFIK_URL}`)
        - traefik.http.services.${TRAEFIK_REF}.loadbalancer.server.port=80
        - homepage.group=Utils
        - homepage.name=Traefik
        - homepage.icon=traefik.png
        - homepage.showstats=true
        - homepage.href=http://${HOST_TRAEFIK_URL}/